# Generated by Django 6.0.3 on 2026-03-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='auteur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='livres', to='api.tag'),
        ),
    ]
